### ISSUE TITLE
Error: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#384]
Updated to the latest HEAD this morning. Got this on restart of the bot.

```
Jun 11 09:20:31 gasgiant python[13806]: Welcome to Poloniex Lending Bot
Jun 11 09:20:31 gasgiant python[13806]: Started WebServer, lendingbot status available at http://10.10.10.202:8000/lendingbot.html
Jun 11 09:20:31 gasgiant python[13806]: WARN: Invalid setting for gapMode, using defaults...
Jun 11 09:20:31 gasgiant python[13806]: 2017-06-11 09:20:31 Error: unsupported operand type(s) for -: 'str' and 'str'
Jun 11 09:20:31 gasgiant python[13806]: Traceback (most recent call last):
Jun 11 09:20:31 gasgiant python[13806]:   File "/usr/src/poloniexlendingbot/lendingbot.py", line 79, in <module>
Jun 11 09:20:31 gasgiant python[13806]:     Lending.lend_all()
Jun 11 09:20:31 gasgiant python[13806]:   File "/usr/src/poloniexlendingbot/modules/Lending.py", line 227, in lend_all
Jun 11 09:20:31 gasgiant python[13806]:     usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
Jun 11 09:20:31 gasgiant python[13806]:   File "/usr/src/poloniexlendingbot/modules/Lending.py", line 398, in lend_cur
Jun 11 09:20:31 gasgiant python[13806]:     orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
Jun 11 09:20:31 gasgiant python[13806]:   File "/usr/src/poloniexlendingbot/modules/Lending.py", line 300, in construct_orders
Jun 11 09:20:31 gasgiant python[13806]:     gap_diff = top_rate - bottom_rate
Jun 11 09:20:31 gasgiant python[13806]: TypeError: unsupported operand type(s) for -: 'str' and 'str'
Jun 11 09:20:31 gasgiant python[13806]: Unhandled error, please open a Github issue so we can fix it!
```

**Comment by utdrmac** [comment]
I believe this happened due to "permission denied" in the API calls to poloniex. My external IP changed and therefore my API calls were being blocked.

This should still be an active issue though to properly catch things like this.

**Comment by jon-rolfe** [comment]
I can confirm this bug, and my API calls should not be blocked (relevant IPs are whitelisted; I just double checked). That said, I have noticed that the site is running kind of slow today. Possibly a response to a request timeout?

**Comment by utdrmac** [comment]
Oh, glad to hear someone else is having issues. My log is flooded with these today:

    2017-06-12 09:52:47 Error: The read operation timed out Requesting returnActiveLoans

I started using a VPN and couldn't tell if it was the VPN or Poloinex at fault.

**Comment by jon-rolfe** [comment]
Yeah, I'm pretty sure this is solidly on Poloniex's side. That said, this seems to be essentially a "cosmetic" issue—when it gets valid data, it works fine. Presumably an easy fix for error handling on request timeout.
