### ISSUE TITLE
Error: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by REZ1DENT3** [BitBotFactory/poloniexlendingbot#389]
rez1dent3@ubuntu1604:~/bot$  python lendingbot.py 
Welcome to Poloniex Lending Bot
WARN: Invalid setting for gapMode, using defaults...
2017-06-14 13:52:18 Error: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "lendingbot.py", line 79, in <module>
    Lending.lend_all()
  File "/home/rez1dent3/bot/modules/Lending.py", line 227, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/rez1dent3/bot/modules/Lending.py", line 398, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/home/rez1dent3/bot/modules/Lending.py", line 300, in construct_orders
    gap_diff = top_rate - bottom_rate
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Unhandled error, please open a Github issue so we can fix it!

**Comment by rnevet** [comment]
Already reported here: https://github.com/BitBotFactory/poloniexlendingbot/issues/384
Thanks!
