### ISSUE TITLE
Crash - No JSON object could be decoded

### ISSUE THREAD

**Issue by Sbf93** [BitBotFactory/poloniexlendingbot#395]
Hello,

the bot worked fine within the last few days, but today it crashed.
I run it on a dedicated server with Windows.

Here is the log:
2017-06-15 11:40:58 Error: No JSON object could be decoded
Traceback (most recent call last):
  File "C:\poloniexlendingbot-master\lendingbot.py", line 78, in <module>
    Lending.cancel_all()
  File "C:\poloniexlendingbot-master\modules\Lending.py", line 176, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "C:\poloniexlendingbot-master\modules\Poloniex.py", line 182, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "C:\poloniexlendingbot-master\modules\Poloniex.py", line 43, in new_method
    return method(self, *arg, **kws)
  File "C:\poloniexlendingbot-master\modules\Poloniex.py", line 129, in api_query
    data = json.loads(ex.read())
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Unhandled error, please open a Github issue so we can fix it!

I hope this information is helpful.

**Comment by rnevet** [comment]
This issue has been fixed since, it's actually a logging error - Poloniex had an error, and the bot failed to parse it.  Please update to latest version.

**Comment by Sbf93** [comment]
Thank you for the answer. I updated to the latest master.

I will let you know, when I encounter a problem again.
