### ISSUE TITLE
How to use plugin AccountStats

### ISSUE THREAD

**Issue by rstormsf** [BitBotFactory/poloniexlendingbot#400]
Just enabled the plugin and getting an error:

```
unsupported operand type(s) for -: 'str' and 'str'
-------
Traceback (most recent call last):
  File "/home/blabla/polobot/poloniexlendingbot/lendingbot.py", line 79, in <module>
    Lending.lend_all()
  File "/home/blabla/polobot/poloniexlendingbot/modules/Lending.py", line 227, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/blabla/polobot/poloniexlendingbot/modules/Lending.py", line 398, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/home/blabla/polobot/poloniexlendingbot/modules/Lending.py", line 300, in construct_orders
    gap_diff = top_rate - bottom_rate
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

**Comment by rstormsf** [comment]
works fine. Never mind. I figured it was something else
