### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by JCBauza** [BitBotFactory/poloniexlendingbot#411]
```
Welcome to Poloniex Lending Bot
2017-06-27 04:21:23 Error: argument of type 'NoneType' is not iterable Requesting returnAvailableAccountBalances
Traceback (most recent call last):
  File "/home/.../poloniexlendingbot/lendingbot.py", line 78, in <module>
    Lending.cancel_all()
  File "/home/.../poloniexlendingbot/modules/Lending.py", line 177, in cancel_all
    available_balances = api.return_available_account_balances('lending')
  File "/home/.../poloniexlendingbot/modules/Poloniex.py", line 168, in return_available_account_balances
    balances = self.api_query('returnAvailableAccountBalances', {"account": account})
  File "/home/.../poloniexlendingbot/modules/Poloniex.py", line 43, in new_method
    return method(self, *arg, **kws)
  File "/home/.../poloniexlendingbot/modules/Poloniex.py", line 125, in api_query
    json_ret = _read_response(ret)
  File "/home/.../poloniexlendingbot/modules/Poloniex.py", line 90, in _read_response
    if 'error' in data:
TypeError: argument of type 'NoneType' is not iterable
Unhandled error, please open a Github issue so we can fix it!
```

**Comment by JCBauza** [comment]
To replicate the issue, set the currencies to analyze to ACTIVE and that's where it fails based on where the error is being generated. I changed it to ALL and it hasn't immediately failed. I'll continue to monitor and report back if there is anything to add. Thanks!

**Comment by mchl18** [comment]
do you mean this?

`# Local Market Analysis: Choose which coins to record the market of in order to analyse them and compute a recommended lending rate.
# Enter ALL to analyse all coins, enter ACTIVE to analyse the markets of any coins you have in your lending account when the bot starts, these can be mixed.
analyseCurrencies = ACTIVE`

i just tried but couldn't reproduce

**Comment by JCBauza** [comment]
It works now... not sure what happened. I always have some sort of balance in the account so if it happens again I'll add more details.

**Comment by Evanito** [comment]
Might have just needed some time to get what you had in your account. Comment again if it happens again.
