### ISSUE TITLE
Error 400 bad request

### ISSUE THREAD

**Issue by mark-995** [BitBotFactory/poloniexlendingbot#412]
Hello I am receiveing this error, i do not understand what is wrong

HTTP Error 400: Bad Request
Your bot id is probably configured incorrectly
-------
Traceback (most recent call last):
  File "/home/markdhn/poloniexlendingbot/lendingbot.py", line 80, in <module>
    PluginsManager.after_lending()
  File "/home/markdhn/poloniexlendingbot/modules/PluginsManager.py", line 41, in after_lending
    plugin.after_lending()
  File "/home/markdhn/poloniexlendingbot/plugins/AccountStats.py", line 43, in after_lending
    self.notify_stats()
  File "/home/markdhn/poloniexlendingbot/plugins/AccountStats.py", line 137, in notify_stats
    self.log.notify(output, self.notify_config)
  File "/home/markdhn/poloniexlendingbot/modules/Logger.py", line 151, in notify
    send_notification(msg, notify_conf)
  File "/home/markdhn/poloniexlendingbot/modules/Notify.py", line 98, in send_notification
    post_to_telegram(msg, nc['telegram_chat_ids'], nc['telegram_bot_id'])
  File "/home/markdhn/poloniexlendingbot/modules/Notify.py", line 50, in post_to_telegram
    raise NotificationException("{0}\n{1}".format(e, msg))
NotificationException: HTTP Error 400: Bad Request
Your bot id is probably configured incorrectly

**Comment by Evanito** [comment]
>Your bot id is probably configured incorrectly

Nothing to see here...

Glad you found a solution.
