### ISSUE TITLE
MarketAnalysis error when there are no loans in the book

### ISSUE THREAD

**Issue by laxdog** [BitBotFactory/poloniexlendingbot#434]
Don't normally see this, but since everyone has pulled all BTC from Polo for BCC, this happened:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dog/MACD_testing/modules/MarketAnalysis.py", line 156, in update_market_thread
    market_data.append(str(raw_data[i]['rate']))
IndexError: list index out of range
```

Easy fix, if there's an IndexError treat the rate as 5% (max allowable)

**Comment by mchl18** [comment]
I would have looked at it but I can't find a line 156 in MarketAnalysis.py. It only has 150 on master.

**Comment by laxdog** [comment]
Yea, it's becuase it's from my fork. There's an open PR.

**Comment by rnevet** [comment]
There was a similar issue that was fixed in the past.
