### ISSUE TITLE
Bitfinex

### ISSUE THREAD

**Issue by coulterj** [BitBotFactory/poloniexlendingbot#441]
I just updated after seeing the new Bitfinex support and am getting an error.

python lendingbot.py

Traceback (most recent call last):
  File "lendingbot.py", line 17, in <module>
    from modules.ExchangeApiFactory import ExchangeApiFactory
  File "/home/coulter/poloniexlendingbot/modules/ExchangeApiFactory.py", line 6, in <module>
    from modules.Bitfinex import Bitfinex
  File "/home/coulter/poloniexlendingbot/modules/Bitfinex.py", line 11, in <module>
    from modules.Bitfinex2Poloniex import Bitfinex2Poloniex
  File "/home/coulter/poloniexlendingbot/modules/Bitfinex2Poloniex.py", line 6, in <module>
    import pytz
ImportError: No module named pytz

**Comment by rnevet** [comment]
Need to install pytz, it's in the docs.
http://poloniexlendingbot.readthedocs.io/en/latest/installation.html#prerequisites
