### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#451]
```
2017-08-10 01:51:06 Error ('Connection aborted.', BadStatusLine("''",)) Requesting https://api.bitfinex.com/v1/lendbook/ETH?limit_asks=100&limit_bids=100
Traceback (most recent call last):
  File "lendingbot.py", line 81, in <module>
    Lending.lend_all()
  File "/usr/src/bitfinex/modules/Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 403, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/usr/src/bitfinex/modules/Lending.py", line 304, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 339, in get_gap_mode_rates
    order_book = construct_order_book(cur)
  File "/usr/src/bitfinex/modules/Lending.py", line 262, in construct_order_book
    loans = api.return_loan_orders(active_cur, loanOrdersRequestLimit[active_cur])
  File "/usr/src/bitfinex/modules/Bitfinex.py", line 106, in return_loan_orders
    bfxResp = self._get(command)
  File "/usr/src/bitfinex/modules/Bitfinex.py", line 71, in _get
    return self._request('get', command)
  File "/usr/src/bitfinex/modules/Bitfinex.py", line 65, in _request
    raise ex
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rnevet** [comment]
Seems to me like a server side issue, we are handling those quietly here:
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/lendingbot.py#L116

Should add an additional one.
