### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by arruah** [BitBotFactory/poloniexlendingbot#458]
Unhandled error, please open a Github issue so we can fix it!
2017-08-16 00:30:51 Error 'exceptions.ValueError' object has no attribute 'code'
Traceback (most recent call last):
  File "lendingbot.py", line 80, in <module>
    Lending.cancel_all()
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Lending.py", line 181, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Poloniex.py", line 181, in return_open_loan_offers
    loan_offers = self.api_query('returnOpenLoanOffers')
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Poloniex.py", line 36, in new_method
    return method(self, *arg, **kws)
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Poloniex.py", line 127, in api_query
    if ex.code == 502 or ex.code in range(520, 526, 1):
AttributeError: 'exceptions.ValueError' object has no attribute 'code'

Unhandled error, please open a Github issue so we can fix it!

**Comment by WesleyThurner** [comment]
@arruah Have you seen this again since the last two commits listed above?

Can this issue be closed?
