### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by arruah** [BitBotFactory/poloniexlendingbot#459]
WARN: [BOT]-xdays's value: '60' is above the maximum limit: 30, which will be used instead.
Welcome to Lending Bot on BITFINEX
2017-08-16 00:37:51 Error conversion
Traceback (most recent call last):
  File "lendingbot.py", line 80, in <module>
    Lending.cancel_all()
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Lending.py", line 182, in cancel_all
    available_balances = api.return_available_account_balances('lending')
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Bitfinex.py", line 181, in return_available_account_balances
    balances = Bitfinex2Poloniex.convertAccountBalances(bfxResp, account)
  File "/media/kamrenov/other/work/poloniexlendingbot/modules/Bitfinex2Poloniex.py", line 109, in convertAccountBalances
    if ((account == '' or account == accountMap[balance['type']])
KeyError: u'conversion'

Unhandled error, please open a Github issue so we can fix it!

**Comment by bgits** [comment]
This seems to be related to special account bitfinex has related to paying users back from the theft. The api always provides this account in the balances. It should be filtered out.

**Comment by rnevet** [comment]
Should be fixed now, please update.
