### ISSUE TITLE
Unhandle error with Bitfinex "Max retries exceeded with url: /v1/history"

### ISSUE THREAD

**Issue by agramajo** [BitBotFactory/poloniexlendingbot#464]
LOG:

2017-08-16 17:00:13 Error HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/history (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f600a3b8c10>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)) Requesting https://api.bitfinex.com/v1/history
Traceback (most recent call last):
  File "lendingbot.py", line 95, in <module>
    PluginsManager.after_lending()
  File "/root/poloniexlendingbot.2/modules/PluginsManager.py", line 40, in after_lending
    plugin.after_lending()
  File "/root/poloniexlendingbot.2/plugins/AccountStats.py", line 44, in after_lending
    self.update_history()
  File "/root/poloniexlendingbot.2/plugins/AccountStats.py", line 62, in update_history
    self.fetch_history(self.api.create_time_stamp(last_time_stamp), sqlite3.time.time())
  File "/root/poloniexlendingbot.2/plugins/AccountStats.py", line 85, in fetch_history
    history = self.api.return_lending_history(first_time_stamp, last_time_stamp - 1, 5000)
  File "/root/poloniexlendingbot.2/modules/Bitfinex.py", line 309, in return_lending_history
    bfxResp = self._post('history', signed_payload)
  File "/root/poloniexlendingbot.2/modules/Bitfinex.py", line 69, in _post
    return self._request('post', command, payload, verify)
  File "/root/poloniexlendingbot.2/modules/Bitfinex.py", line 66, in _request
    raise ex
ConnectionError: HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/history (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f600a3b8c10>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

Unhandled error, please open a Github issue so we can fix it!

**Comment by rnevet** [comment]
@utdrmac I think this might be related to recent changes. :(

**Comment by utdrmac** [comment]
"No address associated with hostname"

You sure?

**Comment by utdrmac** [comment]
My changes haven't been merged in. Is @agramajo using my PR?

**Comment by rnevet** [comment]
@utdrmac I was thinking about the reduction of results in the history request:
https://github.com/BitBotFactory/poloniexlendingbot/blob/master/plugins/AccountStats.py#L85

But you are probably right and this has nothing to do with it...

**Comment by rnevet** [comment]
@agramajo was the bot working at somepoint before or is this a new setup?

**Comment by agramajo** [comment]
It was working, and then show the error.

**Comment by utdrmac** [comment]
There's a 10s sleep per history request that should remove any "too many API calls" issues. Additionally, all of those requests only happen on fresh install. 

```
Failed to establish a new connection: [Errno -5] No address associated with hostname
```

That wording points me towards internet/ISP issues. If there's too many API requests, he would have received that statement as the error and not this.

@agramajo unless you are continuing to receive this error, I think this can be closed.

We can/should add a catch for `HTTPSConnectionPool` to make it cleaner

https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url
