### ISSUE TITLE
Unhandled error: KeyError: u'USD_OMG'

### ISSUE THREAD

**Issue by JCBauza** [BitBotFactory/poloniexlendingbot#479]
Welcome to Lending Bot on BITFINEX
2017-08-21 18:47:50 Error USD_OMG
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/home/jcarlos/poloniexlendingbot/modules/Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/jcarlos/poloniexlendingbot/modules/Lending.py", line 429, in lend_cur
    raise msg
KeyError: u'USD_OMG'

Unhandled error, please open a Github issue so we can fix it!

**Comment by eduardopaula** [comment]
2017-08-22 12:05:29 Error USD_BCH
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "D:\Users\poloniexlendingbot\modules\
Lending.py", line 232, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "D:\Users\poloniexlendingbot\modules\
Lending.py", line 429, in lend_cur
    raise msg
KeyError: u'USD_BCH'

Unhandled error, please open a Github issue so we can fix it!

**Comment by mike4001** [comment]
had this also (but happened only once)

**Comment by eduardopaula** [comment]
I guess is the same error reported on Bug #447

**Comment by JCBauza** [comment]
Closing it as it is the same bug as reported by eduardo #447
