### ISSUE TITLE
"Unhandled error, please open a Github issue so we can fix it!" When losing DNS name resolution

### ISSUE THREAD

**Issue by JCBauza** [BitBotFactory/poloniexlendingbot#494]
I upgraded the firmware on my modem causing the Internet to drop. That in turn caused an unhandled error:

2017-08-26 13:13:37 Error HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/pubticker/dshusd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3a4c80590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) Requesting https://api.bitfinex.com/v1/pubticker/dshusd
Traceback (most recent call last):
  File "lendingbot.py", line 90, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/home/jcarlos/poloniexlendingbot/modules/Data.py", line 85, in update_conversion_rates
    ticker_response = api.return_ticker()
  File "/home/jcarlos/poloniexlendingbot/modules/Bitfinex.py", line 150, in return_ticker
    ticker = self._get('pubticker/'+symbol)
  File "/home/jcarlos/poloniexlendingbot/modules/Bitfinex.py", line 75, in _get
    return self._request('get', command)
  File "/home/jcarlos/poloniexlendingbot/modules/Bitfinex.py", line 69, in _request
    raise ex
ConnectionError: HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/pubticker/dshusd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3a4c80590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

Unhandled error, please open a Github issue so we can fix it!
Traceback (most recent call last):
  File "lendingbot.py", line 137, in <module>
    log.notify("{0}\n-------\n{1}".format(ex, traceback.format_exc()), notify_conf)
  File "/home/jcarlos/poloniexlendingbot/modules/Logger.py", line 155, in notify
    send_notification(msg, notify_conf)
  File "/home/jcarlos/poloniexlendingbot/modules/Notify.py", line 122, in send_notification
    post_to_slack(msg, nc['slack_channels'], nc['slack_token'])
  File "/home/jcarlos/poloniexlendingbot/modules/Notify.py", line 46, in post_to_slack
    response = urllib2.urlopen(url, enc_post_data)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

**Comment by rnevet** [comment]
This is a local issue with your DNS resolution, can we close this ticket?

**Comment by JCBauza** [comment]
It is an unhandled error which I caused but could happen at any time. I guess in my view there needs to be instead of a fatal error perhaps a sleep time before trying again. The lending bot stopped working after that even after the internet came back up.

**Comment by rnevet** [comment]
If this happens during runtime the bot will continue after sleeping, this is handled in the bot loop.

**Comment by JCBauza** [comment]
It was during run time and it stopped working. Sometimes I guess the loop doesn't work in my experience... having that issues right now with the "Error list index out of range." Eventually it crashes for good.
