### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by eduardopaula** [BitBotFactory/poloniexlendingbot#512]
I've checkout the lastest version of poloniexlendingbot, but the issue continues.
My default.cfg 

https://pastebin.com/gMgRuz08

This is the error:

Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "D:\Users\poloniexlendingbot\modules\Lending.py", line 244, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "D:\Users\poloniexlendingbot\modules\Lending.py", line 415, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "D:\Users\poloniexlendingbot\modules\Lending.py", line 316, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "D:\Users\poloniexlendingbot\modules\Lending.py", line 368, in get_gap_mode_rates
    bottom_rate = get_gap_rate(cur, bottom_depth, order_book, cur_total_balance, True)
  File "D:\Users\poloniexlendingbot\modules\Lending.py", line 303, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

**Comment by laxdog** [comment]
Hey @eduardopaula , thanks for the bug report. 

I think this is the same as https://github.com/BitBotFactory/poloniexlendingbot/issues/514

We'll probably be tracking it there.
