### ISSUE TITLE
HISTORY_DUMP from config

### ISSUE THREAD

**Issue by MoonMaker** [BitBotFactory/poloniexlendingbot#517]
Hello,

HISTORY_DUMP = "www/history.json" is defined static in code. And when I'm changing the name of www folder, the following error is given:

Short higher: 2017-09-17 14:10:52 Error 
Traceback (most recent call last):
  File "/opt/poloniexlendingbot/lendingbot.py", line 95, in <module>
    PluginsManager.after_lending()
  File "/opt/poloniexlendingbot/modules/PluginsManager.py", line 47, in after_lending
    plugin.after_lending()
  File "/opt/poloniexlendingbot/plugins/Charts.py", line 33, in after_lending
    self.dump_history()
  File "/opt/poloniexlendingbot/plugins/Charts.py", line 63, in dump_history
    with open(HISTORY_DUMP, "w") as hist:
IOError: [Errno 2] No such file or directory: 'www/history.json'

Could you please add "historyfile" to config file like it is done for jsonfile? 

jsonfile = www-myown/botlog.json

Thanks!

Best regards,

Thomas

**Comment by utdrmac** [comment]
@MoonMaker Please test out the linked PR please.
