### ISSUE TITLE
DNS Error

### ISSUE THREAD

**Issue by adonaicanez** [BitBotFactory/poloniexlendingbot#524]
```
Unhandled error, please open a Github issue so we can fix it!
2017-09-19 22:04:36 Error ('Connection aborted.', gaierror(-5, 'No address associated with hostname')) Requesting https://api.bitfinex.com/v1/lendbook/ZEC?limit_asks=100&limit_bids=100
Traceback (most recent call last):
  File "/home/adonai/bitfinexlendingbot/lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/home/adonai/bitfinexlendingbot/modules/Lending.py", line 244, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/adonai/bitfinexlendingbot/modules/Lending.py", line 403, in lend_cur
    order_book = construct_order_book(active_cur)
  File "/home/adonai/bitfinexlendingbot/modules/Lending.py", line 274, in construct_order_book
    loans = api.return_loan_orders(active_cur, loanOrdersRequestLimit[active_cur])
  File "/home/adonai/bitfinexlendingbot/modules/Bitfinex.py", line 150, in return_loan_orders
    bfx_resp = self._get(command)
  File "/home/adonai/bitfinexlendingbot/modules/Bitfinex.py", line 120, in _get
    return self._request('get', request)
  File "/home/adonai/bitfinexlendingbot/modules/ExchangeApi.py", line 29, in new_method
    return method(self, *arg, **kws)
  File "/home/adonai/bitfinexlendingbot/modules/Bitfinex.py", line 109, in _request
    raise ex
ConnectionError: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by utdrmac** [comment]
You have DNS issues. Your computer cannot resolve api.bitfinex.com. Try changing your DNS settings.

**Comment by laxdog** [comment]
Is this a recurring issue @adonaicanez ?

Looks like it could have just been a blip in either the Bitfinex site or your DNS settings. 

I think it's possible to get this error when cloudflare handles the response also.

**Comment by laxdog** [comment]
No update, closing
