### ISSUE TITLE
 Error USD_NEO BITFINEX

### ISSUE THREAD

**Issue by tonymorella** [BitBotFactory/poloniexlendingbot#545]
```
2017-09-29 00:08:29 Error USD_NEO
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/opt/trading/poloniexlendingbot/modules/Lending.py", line 248, in lend_all
    lend_all()
  File "/opt/trading/poloniexlendingbot/modules/Lending.py", line 248, in lend_all
    lend_all()
  File "/opt/trading/poloniexlendingbot/modules/Lending.py", line 246, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/opt/trading/poloniexlendingbot/modules/Lending.py", line 443, in lend_cur
    raise msg
KeyError: u'USD_NEO'

Unhandled error, please open a Github issue so we can fix it!
```

**Comment by nicokacz** [comment]
I have modified modules/Bitfinex.py, l.282 : 
`if currency != 'USD' and currency != 'NEO':`
Just avoid to find the "lowestAsk" for NEO, which is raising exception.
I think it's not a good solution for long term but at least the report is well generated now.

FYI : lowestAsk is not send back by Bitfinex API "pubticker" so I don't know how this could work.

**Comment by eduardbader** [comment]
just add NEO to your config file, in _all_currencies_ list

**Comment by utdrmac** [comment]
@tonymorella Is this resolved with the solution given? Please close this issue if so. Thanks.
