### ISSUE TITLE
AttributeError: 'exceptions.ValueError' object has no attribute 'code'

### ISSUE THREAD

**Issue by iamraa** [BitBotFactory/poloniexlendingbot#548]
```
Unhandled error, please open a Github issue so we can fix it!                                                        
Traceback (most recent call last):                                                                                   
  File "/home/bot/data/lending/bot-poloniex/lendingbot.py", line 81, in <module>                                     
    Lending.lend_all()                                                                                               
  File "/home/bot/data/lending/bot-poloniex/modules/Lending.py", line 211, in lend_all                               
    total_lent = Data.get_total_lent()[0]                                                                            
  File "/home/bot/data/lending/bot-poloniex/modules/Data.py", line 44, in get_total_lent                             
    crypto_lent = api.return_active_loans()                                                                          
  File "/home/bot/data/lending/bot-poloniex/modules/Poloniex.py", line 187, in return_active_loans                   
    return self.api_query('returnActiveLoans')                                                                       
  File "/home/bot/data/lending/bot-poloniex/modules/Poloniex.py", line 36, in new_method                             
    return method(self, *arg, **kws)                                                                                 
  File "/home/bot/data/lending/bot-poloniex/modules/Poloniex.py", line 127, in api_query                             
    if ex.code == 502 or ex.code in range(520, 526, 1):                                                              
AttributeError: 'exceptions.ValueError' object has no attribute 'code'
```

**Comment by Evanito** [comment]
Hey, try updating to the most recent version that has some more stuff to help us with debugging. 

If this happens again, post that log. Thanks.

**Comment by laxdog** [comment]
No update, closing
