### ISSUE TITLE
email error

### ISSUE THREAD

**Issue by mmoroni75** [BitBotFactory/poloniexlendingbot#559]
On Bitfinex,
```
Could not send email, got error Connection unexpectedly closed
Error during summary notification: Connection unexpectedly closed
Could not send email, got error Connection unexpectedly closed
2017-10-12 16:12:10 Error Connection unexpectedly closed
Traceback (most recent call last):
  File "lendingbot.py", line 95, in <module>
    PluginsManager.after_lending()
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/PluginsManager.py", line 47, in after_lending
    plugin.after_lending()
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/plugins/AccountStats.py", line 48, in after_lending
    self.notify_stats()
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/plugins/AccountStats.py", line 181, in notify_stats
    self.log.notify(output, self.notify_config)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Logger.py", line 168, in notify
    send_notification(msg, notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Notify.py", line 122, in send_notification
    nc['email_smtp_port'], nc['email_to_addresses'], nc['email_smtp_starttls'])
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Notify.py", line 86, in send_email
    raise NotificationException(e)
NotificationException: Connection unexpectedly closed

v3.0.0 Unhandled error, please open a Github issue so we can fix it!
Could not send email, got error Connection unexpectedly closed
Traceback (most recent call last):
  File "lendingbot.py", line 144, in <module>
    log.notify("{0}\n-------\n{1}".format(ex, traceback.format_exc()), notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Logger.py", line 168, in notify
    send_notification(msg, notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Notify.py", line 122, in send_notification
    nc['email_smtp_port'], nc['email_to_addresses'], nc['email_smtp_starttls'])
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Notify.py", line 86, in send_email
    raise NotificationException(e)
modules.Notify.NotificationException: Connection unexpectedly closed

```

**Comment by rnevet** [comment]
Have you resolve this?

**Comment by laxdog** [comment]
Same with this one @mmoroni75 , closing soon.

**Comment by vmroa** [comment]
any advance on this issue? i have the same problem
