### ISSUE TITLE
API ERROR During operations on Bitfinex

### ISSUE THREAD

**Issue by mmoroni75** [BitBotFactory/poloniexlendingbot#563]
Hi all, I had this error during 

v3.0.0 Unhandled error, please open a Github issue so we can fix it!
2017-10-15 21:05:49 Error API Error 502: The web server reported a bad gateway or gateway timeout error. Requesting https://api.bitfinex.com/v1/offers
Caught API Error 502: The web server reported a bad gateway or gateway timeout error. Requesting https://api.bitfinex.com/v1/offers reading from exchange API, ignoring.
2017-10-16 03:31:14 Error ('Connection aborted.', gaierror(-2, 'Name or service not known')) Requesting https://api.bitfinex.com/v1/credits
Traceback (most recent call last):
  File "lendingbot.py", line 90, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Data.py", line 84, in update_conversion_rates
    total_lent = get_total_lent()[0]
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Data.py", line 44, in get_total_lent
    crypto_lent = api.return_active_loans()
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Bitfinex.py", line 156, in return_active_loans
    bfx_resp = self._post('credits')
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/ExchangeApi.py", line 29, in new_method
    return method(self, *arg, **kws)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Bitfinex.py", line 108, in _post
    return self._request('post', payload['request'], signed_payload, verify)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-20171012/modules/Bitfinex.py", line 97, in _request
    raise ex
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by rnevet** [comment]
Those are 2 errors, the first a 502 is Bitfinex fault. the 2nd is a DNS issue on your machine. 

If the bot is otherwise working properly then there is nothing to be done.
