### ISSUE TITLE
Email Connection Error

### ISSUE THREAD

**Issue by mmoroni75** [BitBotFactory/poloniexlendingbot#564]
v3.0.0 Unhandled error, please open a Github issue so we can fix it!
Could not send email, got error Connection unexpectedly closed
Traceback (most recent call last):
  File "lendingbot.py", line 144, in <module>
    log.notify("{0}\n-------\n{1}".format(ex, traceback.format_exc()), notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-ric-20171012/modules/Logger.py", line 168, in notify
    send_notification(msg, notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-ric-20171012/modules/Notify.py", line 122, in send_notification
    nc['email_smtp_port'], nc['email_to_addresses'], nc['email_smtp_starttls'])
  File "/home/mmoroni/poloniexlendingbot-bitfinex-ric-20171012/modules/Notify.py", line 86, in send_email
    raise NotificationException(e)
modules.Notify.NotificationException: Connection unexpectedly closed

**Comment by rnevet** [comment]
Duplicate #559
