### ISSUE TITLE
Irc unhandled error

### ISSUE THREAD

**Issue by mmoroni75** [BitBotFactory/poloniexlendingbot#565]
```
v3.0.0 Unhandled error, please open a Github issue so we can fix it!
Traceback (most recent call last):
  File "lendingbot.py", line 144, in <module>
    log.notify("{0}\n-------\n{1}".format(ex, traceback.format_exc()), notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-ric-20171012/modules/Logger.py", line 168, in notify
    send_notification(msg, notify_conf)
  File "/home/mmoroni/poloniexlendingbot-bitfinex-ric-20171012/modules/Notify.py", line 132, in send_notification
    nc['irc_target'])
  File "/home/mmoroni/poloniexlendingbot-bitfinex-ric-20171012/modules/Notify.py", line 113, in post_to_irc
    IRC_SERVER.privmsg(target, msg)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 804, in privmsg
    self.send_items('PRIVMSG', target, ':' + text)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 835, in send_items
    self.send_raw(' '.join(filter(None, items)))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 846, in send_raw
    sender(self._prep_message(string))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 822, in _prep_message
    raise InvalidCharacters(msg)
irc.client.InvalidCharacters: Carriage returns not allowed in privmsg(text)
```

**Comment by grenade** [comment]
i also just got this error...

```
2017-11-13 18:39:52 Error Carriage returns not allowed in privmsg(text)
Traceback (most recent call last):
  File "lendingbot.py", line 95, in <module>
    PluginsManager.after_lending()
  File "/home/ubuntu/poloniexlendingbot/modules/PluginsManager.py", line 47, in after_lending
    plugin.after_lending()
  File "/home/ubuntu/poloniexlendingbot/plugins/AccountStats.py", line 48, in after_lending
    self.notify_stats()
  File "/home/ubuntu/poloniexlendingbot/plugins/AccountStats.py", line 181, in notify_stats
    self.log.notify(output, self.notify_config)
  File "/home/ubuntu/poloniexlendingbot/modules/Logger.py", line 168, in notify
    send_notification(msg, notify_conf)
  File "/home/ubuntu/poloniexlendingbot/modules/Notify.py", line 132, in send_notification
    nc['irc_target'])
  File "/home/ubuntu/poloniexlendingbot/modules/Notify.py", line 113, in post_to_irc
    IRC_SERVER.privmsg(target, msg)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 828, in privmsg
    self.send_items('PRIVMSG', target, ':' + text)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 859, in send_items
    self.send_raw(' '.join(filter(None, items)))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 870, in send_raw
    sender(self._prep_message(string))
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 846, in _prep_message
    raise InvalidCharacters(msg)
InvalidCharacters: Carriage returns not allowed in privmsg(text)
```

**Comment by laxdog** [comment]
@mmoroni75 Can you confirm this is working and close the issue if so?
