### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/poloniexlendingbot#566]
Config: http://termbin.com/anja

```
Welcome to "Bitfinex Lending Bot" on BITFINEX
ETH : Need more data for analysis, still collecting. I have 242/270 records
Caught exception during MACD analysis, using percentile for now
ETH : Need more data for analysis, still collecting. I have 245/270 records
Caught exception during MACD analysis, using percentile for now
BCH : Need more data for analysis, still collecting. I have 243/270 records
Caught exception during MACD analysis, using percentile for now
2017-10-23 12:50:55 Error list index out of range
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/usr/src/bitfinex/modules/Lending.py", line 249, in lend_all
    lend_all()
  File "/usr/src/bitfinex/modules/Lending.py", line 247, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 444, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/usr/src/bitfinex/modules/Lending.py", line 345, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/usr/src/bitfinex/modules/Lending.py", line 399, in get_gap_mode_rates
    top_rate = get_gap_rate(cur, top_depth, order_book, cur_total_balance, True)
  File "/usr/src/bitfinex/modules/Lending.py", line 332, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v343
 Unhandled error, please open a Github issue so we can fix it!
```

**Comment by rurara** [comment]
File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/data/www/poloniexlendingbot/modules/Lending.py", line 247, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/data/www/poloniexlendingbot/modules/Lending.py", line 418, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/data/www/poloniexlendingbot/modules/Lending.py", line 319, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/data/www/poloniexlendingbot/modules/Lending.py", line 373, in get_gap_mode_rates
    top_rate = get_gap_rate(cur, top_depth, order_book, cur_total_balance, True)
  File "/data/www/poloniexlendingbot/modules/Lending.py", line 306, in get_gap_rate 
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v311
 Unhandled error, please open a Github issue so we can fix it!

**Comment by laxdog** [comment]
Again, I think this is a corrupted DB.

**Comment by utdrmac** [comment]
How can the DB be corrupted between intervals? It's not like the db corrupts and then the bot crashes. You get these randomly but everything continues working again a few cycles later.

**Comment by Evanito** [comment]
Lots of reports for this same error recently. We should either:
* Find cause and fix.
* Skip events which would cause this error, as long as it isn't fatal.

The second one is likely better.  And it appears that the error just coincidentally appeared alongside some DB work.

**Comment by Evanito** [comment]
https://github.com/BitBotFactory/poloniexlendingbot/blob/ce424469ee9c684d720be106f6dc1f57547d1544/modules/Lending.py#L328

https://github.com/BitBotFactory/poloniexlendingbot/blob/ce424469ee9c684d720be106f6dc1f57547d1544/modules/Lending.py#L333

Two instances where you get an off by one error due to comparing an iterator to the length. Oops. Fix coming shortly.
