### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nickfost** [BitBotFactory/poloniexlendingbot#578]
2017-11-05 08:55:18 Canceling DOGE order... Loan offer canceled.
2017-11-05 08:55:32 Not lending MAID due to rate below 0.0030% (actual: 0.0001%)

2017-11-05 08:55:36 Not lending ETH due to rate below 0.0030% (actual: 0.0002%)
2017-11-05 08:55:41 Placing 17.16251597 CLAM at 4.9999% for 60 days... Loan orde
r placed.
2017-11-05 08:55:46 Error list index out of range
Lent: [1.7374 BTC @ 0.0069%] [0.9197 DASH @ 0.0041%] [12094.9606 DOGE @ 0.00...T
raceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 247, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 418, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance,
ticker)  # Build all potential orders
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 319, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_ba
lance, ticker)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 371, in get_gap_mode_rates
    bottom_rate = get_gap_rate(cur, bottom_depth, order_book, cur_total_balance,
 True)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 306, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v311
 Unhandled error, please open a Github issue so we can fix it!
2017-11-05 08:56:52 Canceling CLAM order... Loan offer canceled.
2017-11-05 08:57:00 Not lending MAID due to rate below 0.0030% (actual: 0.0001%)

2017-11-05 08:57:03 Not lending ETH due to rate below 0.0030% (actual: 0.0002%)
2017-11-05 08:57:09 Placing 17.16251597 CLAM at 4.9999% for 60 days... Loan orde
r placed.
2017-11-05 08:57:14 Error list index out of range
Lent: [1.7374 BTC @ 0.0069%] [0.9197 DASH @ 0.0041%] [12094.9606 DOGE @ 0.00...T
raceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 247, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 418, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance,
ticker)  # Build all potential orders
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 319, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_ba
lance, ticker)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 371, in get_gap_mode_rates
    bottom_rate = get_gap_rate(cur, bottom_depth, order_book, cur_total_balance,
 True)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 306, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v311
 Unhandled error, please open a Github issue so we can fix it!

**Comment by Nickfost** [comment]
more 



2017-11-11 21:34:48 Error The read operation timed out Requesting createLoanOffe
r
Timed out, will retry in 60.0sec
2017-11-11 21:45:45 Error The read operation timed out Requesting returnActiveLo
ans
Timed out, will retry in 60.0sec
2017-11-11 21:47:29 Error list index out of range
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 247, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 418, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance,
ticker)  # Build all potential orders
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 319, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_ba
lance, ticker)
  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 373, in get_gap_mode_rates
    top_rate = get_gap_rate(cur, top_depth, order_book, cur_total_balance, True)

  File "X:\Bittorrent Sync\Documents\PLB\poloniexlendingbot\modules\Lending.py",
 line 306, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v311
 Unhandled error, please open a Github issue so we can fix it!

**Comment by laxdog** [comment]
Looks like there was a timeout at the exchange just @Nickfost 

Is this still happening?

Did the bot actually work?

**Comment by Nickfost** [comment]
Yeah it’s not handling connection loss very well. I would imagine you shouldn’t assume the exchange is always up or the host connection is always available. better handling of this scenario would be much appreciated.



Nick Foster
-----------------
me@nickfost.com

**Comment by rnevet** [comment]
The bot handles itself great, it just also logs the errors... There is no assumption what so ever that the service is always available.

**Comment by rnevet** [comment]
Specifically "list index out of range" is probably a result of a malformed response from the server which the bot should handle better - but in any case it will continue working.

**Comment by Nickfost** [comment]
As an example of an error that might need to be handled better.... 

"

2017-11-19 01:00:16 Error HTTP Error 422: Requesting returnAvailableAccountBalances. Poloniex reports: 'Nonce must be greater than 1511074816381. You provided 1511074814969.'
--

"


this hung my bot up for 5 hours until i noticed and restarted it.

**Comment by laxdog** [comment]
That shouldn't be happening unless you are running multiple bots, or your session has got messed up somehow.

**Comment by Nickfost** [comment]
Still happens every other minute. Not running multiple instances.



Nick Foster
-----------------
me@nickfost.com

**Comment by laxdog** [comment]
OK, can you try creating a new API key and put that in the bot. It sounds like something is wrong with the current one.
