### ISSUE TITLE
[Error] Synthax

### ISSUE THREAD

**Issue by Sigri44** [BitBotFactory/poloniexlendingbot#601]
Hi guys,

I'm french user, thx for this bot !
But i have an error : 

Python 2.7.13 : 
```
root@docker ~/ # python lendingbot.py
Traceback (most recent call last):
  File "lendingbot.py", line 17, in <module>
    from modules.ExchangeApiFactory import ExchangeApiFactory
  File "/root/scripts/poloniexlendingbot/modules/ExchangeApiFactory.py", line 6, in <module>
    from modules.Bitfinex import Bitfinex
  File "/root/scripts/poloniexlendingbot/modules/Bitfinex.py", line 6, in <module>
    import requests
ImportError: No module named requests
```
```
~/ # pip3 install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages
```

Python 3.5.3 : 
```
root@docker ~/ # python3 lendingbot.py
  File "lendingbot.py", line 85
    print 'Welcome to ' + Config.get("BOT", "label", "Lending Bot") + ' on ' + exchange
                      ^
SyntaxError: invalid syntax
```

I  don't understand why there is an error.. I have 2 version of Python, pip, is always installed, i have reinstall it on python 2 & 3 and it say "pip is always installer on /repository".

Thank you !

**Comment by rnevet** [comment]
1. The bot doesn't support Python 3.
2. You are using 'pip**3**' to install requests.
