### ISSUE TITLE
New version of the bot errors out on old working config

### ISSUE THREAD

**Issue by slakos-slakos** [BitBotFactory/poloniexlendingbot#609]
$ python lendingbot.py 
Welcome to Lending Bot on POLONIEX
2018-02-11 12:15:20 Error frrasmin
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/home/skosoy/Desktop/poloniexlendingbot/modules/Lending.py", line 252, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/skosoy/Desktop/poloniexlendingbot/modules/Lending.py", line 433, in lend_cur
    cur_min_daily_rate = get_min_daily_rate(active_cur)
  File "/home/skosoy/Desktop/poloniexlendingbot/modules/Lending.py", line 285, in get_min_daily_rate
    cur_min_daily_rate = get_frr_or_min_daily_rate(cur)
  File "/home/skosoy/Desktop/poloniexlendingbot/modules/Lending.py", line 268, in get_frr_or_min_daily_rate
    frrasmin = coin_cfg[cur]['frrasmin']
KeyError: 'frrasmin'

v316
 Unhandled error, please open a Github issue so we can fix it!
2018-02-11 12:15:22 bye
bye

**Comment by Nitro888** [comment]
'Error frrasmin' - I have same error.

**Comment by vtwizzie** [comment]
Same error coming up here.

**Comment by lexrms** [comment]
Similar here:
I have #frrasmin commented

Welcome to Lending Bot on POLONIEX
2018-02-14 16:37:10 Error 'bool' object is not iterable
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/home/leo/python/poloniexlendingbot/modules/Lending.py", line 252, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/leo/python/poloniexlendingbot/modules/Lending.py", line 449, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/home/leo/python/poloniexlendingbot/modules/Lending.py", line 350, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/home/leo/python/poloniexlendingbot/modules/Lending.py", line 397, in get_gap_mode_rates
    for coin in ticker:
TypeError: 'bool' object is not iterable

v317
 Unhandled error, please open a Github issue so we can fix it!

**Comment by rnevet** [comment]
Issue is related to coin config and latest frr as min change, specific line:
https://github.com/BitBotFactory/poloniexlendingbot/blob/fcd3fbb83797cb636a55b9059d8273b071c2beaa/modules/Lending.py#L268

Assumes that frrasmin is present.

**Comment by rnevet** [comment]
Are you using "old" coinconfig line configuration?

**Comment by Nitro888** [comment]
remove and re-install again. and use new default.cfg.
But It has same bug.

**Comment by rnevet** [comment]
@Nitro888  are you using coinconfig line configuration?

**Comment by Nitro888** [comment]
you mean this line?
'coinconfig = ["BTC:0.18:1:0:0:0","CLAM:0.6:1:0:0:0"]'
yes i'm using it.  is this old?

**Comment by rnevet** [comment]
"oldish", anyway the implementation of frrmin didn't take this into consideration, use the segment coin config. 

We will remove the coincfg one line in the future anyway.

**Comment by Nitro888** [comment]
Thanks. It works.

**Comment by rnevet** [comment]
That's great, I made a PR and coinconfig will be removed from the configuration options.
