### ISSUE TITLE
Fatal error .git

### ISSUE THREAD

**Issue by easye35** [BitBotFactory/poloniexlendingbot#658]
```
nginx_1     | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx_1     | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx_1     | forego     | starting dockergen.1 on port 5000
nginx_1     | forego     | starting nginx.1 on port 5100
nginx_1     | dockergen.1 | 2021/04/20 21:27:42 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx_1     | dockergen.1 | 2021/04/20 21:27:42 Watching docker events
nginx_1     | dockergen.1 | 2021/04/20 21:27:42 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx_1     | 2021/04/20 21:27:46 [notice] 45#45: signal process started
nginx_1     | Generating DSA parameters, 4096 bit long prime
nginx_1     | dhparam generation complete, reloading nginx
nginx_1     | dockergen.1 | 2021/04/20 21:28:52 Received event die for container 30d61395f501
nginx_1     | dockergen.1 | 2021/04/20 21:28:52 Received event stop for container 30d61395f501
nginx_1     | dockergen.1 | 2021/04/20 21:28:52 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx_1     | dockergen.1 | 2021/04/20 21:28:52 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx_1     | dockergen.1 | 2021/04/20 21:28:53 Received event start for container c971f502c50a
nginx_1     | dockergen.1 | 2021/04/20 21:28:53 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx_1     | dockergen.1 | 2021/04/20 21:28:53 Running 'nginx -s reload'
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:30:18 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:30:18 +0000] "GET /images/icon384.png HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:30:18 +0000] "GET /images/icon.ico HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:30:47 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:31:47 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:32:48 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:33:48 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:34:48 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:35:48 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:36:48 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1     | nginx.1    | 74.208.253.224 75.155.43.86 - - [20/Apr/2021:21:37:48 +0000] "GET /botlog.json HTTP/1.1" 503 197 "http://74.208.253.224/lendingbot.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"
poloniex_1  | unlink: cannot unlink '/usr/git-src/cad.ourbtcsite.ca-botlog.json': No such file or directory
poloniex_1  | rm: cannot remove '/usr/src/app/www/botlog.json': No such file or directory
poloniex_1  | Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (1.15.1)
poloniex_1  | Requirement already satisfied: pandas in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.23.4)
poloniex_1  | Collecting hypothesis (from -r requirements.txt (line 3))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/a2/c8/de039e5fb476ed73cb4d6d98a1fee68b0b26f13729cfcccfc32647476ab2/hypothesis-4.57.1.tar.gz (233kB)
poloniex_1  | Collecting requests (from -r requirements.txt (line 4))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
poloniex_1  | Requirement already satisfied: pytz in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2018.5)
poloniex_1  | Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python2.7/site-packages (from pandas->-r requirements.txt (line 2)) (2.7.3)
poloniex_1  | Collecting attrs>=19.2.0 (from hypothesis->-r requirements.txt (line 3))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/c3/aa/cb45262569fcc047bf070b5de61813724d6726db83259222cd7b4c79821a/attrs-20.3.0-py2.py3-none-any.whl (49kB)
poloniex_1  | Collecting sortedcontainers<3.0.0,>=2.1.0 (from hypothesis->-r requirements.txt (line 3))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/20/4d/a7046ae1a1a4cc4e9bbed194c387086f06b25038be596543d026946330c9/sortedcontainers-2.3.0-py2.py3-none-any.whl
poloniex_1  | Collecting enum34 (from hypothesis->-r requirements.txt (line 3))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
poloniex_1  | Collecting urllib3<1.27,>=1.21.1 (from requests->-r requirements.txt (line 4))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/09/c6/d3e3abe5b4f4f16cf0dfc9240ab7ce10c2baa0e268989a4e3ec19e90c84e/urllib3-1.26.4-py2.py3-none-any.whl (153kB)
poloniex_1  | Collecting idna<3,>=2.5 (from requests->-r requirements.txt (line 4))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
poloniex_1  | Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 4))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
poloniex_1  | Collecting chardet<5,>=3.0.2 (from requests->-r requirements.txt (line 4))
poloniex_1  |   Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
poloniex_1  | Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas->-r requirements.txt (line 2)) (1.11.0)
poloniex_1  | Building wheels for collected packages: hypothesis
poloniex_1  |   Running setup.py bdist_wheel for hypothesis: started
poloniex_1  |   Running setup.py bdist_wheel for hypothesis: finished with status 'done'
poloniex_1  |   Stored in directory: /root/.cache/pip/wheels/55/45/60/fe3f7b7d6fcdda1a8efaf0eb526d759dfa79a81ea785f0751b
poloniex_1  | Successfully built hypothesis
poloniex_1  | Installing collected packages: attrs, sortedcontainers, enum34, hypothesis, urllib3, idna, certifi, chardet, requests
poloniex_1  | Successfully installed attrs-20.3.0 certifi-2020.12.5 chardet-4.0.0 enum34-1.1.10 hypothesis-4.57.1 idna-2.10 requests-2.25.1 sortedcontainers-2.3.0 urllib3-1.26.4
poloniex_1  | You are using pip version 18.0, however version 20.3.4 is available.
poloniex_1  | You should consider upgrading via the 'pip install --upgrade pip' command.
poloniex_1  | fatal: Not a git repository (or any of the parent directories): .git
poloniex_1  | Starting WebServer at 0.0.0.0 on port 8000 with template www
poloniex_1  | Started WebServer, lendingbot status available at http://172.26.0.3:8000/lendingbot.html, http://127.0.0.1:8000/lendingbot.html
poloniex_1  | Could not send email, got error Connection unexpectedly closed
poloniex_1  | 2021-04-20 21:29:13 Error Connection unexpectedly closed
poloniex_1  | Traceback (most recent call last):
poloniex_1  |   File "lendingbot.py", line 115, in <module>
poloniex_1  |     PluginsManager.after_lending()
poloniex_1  |   File "/usr/src/app/modules/PluginsManager.py", line 47, in after_lending
poloniex_1  |     plugin.after_lending()
poloniex_1  |   File "/usr/src/app/plugins/AccountStats.py", line 48, in after_lending
poloniex_1  |     self.notify_stats()
poloniex_1  |   File "/usr/src/app/plugins/AccountStats.py", line 181, in notify_stats
poloniex_1  |     self.log.notify(output, self.notify_config)
poloniex_1  |   File "/usr/src/app/modules/Logger.py", line 168, in notify
poloniex_1  |     send_notification(msg, notify_conf)
poloniex_1  |   File "/usr/src/app/modules/Notify.py", line 123, in send_notification
poloniex_1  |     nc['email_smtp_port'], nc['email_to_addresses'], nc['email_smtp_starttls'])
poloniex_1  |   File "/usr/src/app/modules/Notify.py", line 86, in send_email
poloniex_1  |     raise NotificationException(e)
poloniex_1  | NotificationException: Connection unexpectedly closed
poloniex_1  |
poloniex_1  | v3.0.0 Unhandled error, please open a Github issue so we can fix it!
```

**Comment by easye35** [comment]
https://pastebin.com/59Xgi43U

**Comment by Evanito** [comment]
Seems to be a problem with the email plugin. Is it properly configured?

**Comment by easye35** [comment]
I only get these errors when VIRTUAL_HOST=SUB.MYDOMAIN.COM
works great when it's VIRTUAL_HOST=12.12.12.12
I can view server when VH=ip
Can't view when VH=Mydomain

Removed email for now, this is what I have in docker config

https://pastebin.com/LF2N2rJR
