### ISSUE TITLE
Broken pipe when running from domain

### ISSUE THREAD

**Issue by easye35** [BitBotFactory/poloniexlendingbot#659]
Traceback (most recent call last):
poloniex_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
poloniex_1  |     self.process_request(request, client_address)
poloniex_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
poloniex_1  |     self.finish_request(request, client_address)
poloniex_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
poloniex_1  |     self.RequestHandlerClass(request, client_address, self)
poloniex_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 654, in __init__
poloniex_1  |     self.finish()
poloniex_1  |   File "/usr/local/lib/python2.7/SocketServer.py", line 713, in finish
poloniex_1  |     self.wfile.close()
poloniex_1  |   File "/usr/local/lib/python2.7/socket.py", line 283, in close
poloniex_1  |     self.flush()
poloniex_1  |   File "/usr/local/lib/python2.7/socket.py", line 307, in flush
poloniex_1  |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
poloniex_1  | error: [Errno 32] Broken pipe

**Comment by easye35** [comment]
was an issue with dns server...not script
