### ISSUE TITLE
Error local variable 'ex' referenced before assignment

### ISSUE THREAD

**Issue by easye35** [BitBotFactory/poloniexlendingbot#660]
Keep getting this error on the log

Traceback (most recent call last):
poloniex_1  |   File "/usr/src/app/lendingbot.py", line 97, in <module>
poloniex_1  |     Lending.transfer_balances()
poloniex_1  |   File "/usr/src/app/modules/Lending.py", line 454, in transfer_balances
poloniex_1  |     exchange_balances = api.return_balances()  # This grabs only exchange balances.
poloniex_1  |   File "/usr/src/app/modules/Poloniex.py", line 169, in return_balances
poloniex_1  |     return self.api_query('returnBalances')
poloniex_1  |   File "/usr/src/app/modules/ExchangeApi.py", line 29, in new_method
poloniex_1  |     return method(self, *arg, **kws)
poloniex_1  |   File "/usr/src/app/modules/Poloniex.py", line 141, in api_query
poloniex_1  |     ex.message = ex.message if hasattr(ex, 'message') and ex.message else str(ex)
poloniex_1  | UnboundLocalError: local variable 'ex' referenced before assignment
poloniex_1  |
poloniex_1  | Unhandled error, please open a Github issue so we can fix it!

**Comment by easye35** [comment]
Traceback (most recent call last):
tindolt_1   |   File "lendingbot.py", line 97, in <module>
tindolt_1   |     Lending.transfer_balances()
tindolt_1   |   File "/usr/src/app/modules/Lending.py", line 454, in transfer_balances
tindolt_1   |     exchange_balances = api.return_balances()  # This grabs only exchange balances.
tindolt_1   |   File "/usr/src/app/modules/Poloniex.py", line 169, in return_balances
tindolt_1   |     return self.api_query('returnBalances')
tindolt_1   |   File "/usr/src/app/modules/ExchangeApi.py", line 29, in new_method
tindolt_1   |     return method(self, *arg, **kws)
tindolt_1   |   File "/usr/src/app/modules/Poloniex.py", line 143, in api_query
tindolt_1   |     raise ex
tindolt_1   | ValueError: No JSON object could be decoded

**Comment by easye35** [comment]
Seems that it only happens when Poloniex is giving a 502 error msg

**Comment by rnevet** [comment]
There should be error handling for error 502, maybe Polo changed something.

**Comment by easye35** [comment]
I see that section in poloniex.py. But that's where the error coming from. not sure why though, doesn't seem to be handling error. At least that's what it looks like to me.
