### ISSUE TITLE
Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by linearniyali** [BitBotFactory/poloniexlendingbot#661]
Traceback (most recent call last):
  File "/home/linear/poloniexlendingbot/lendingbot.py", line 113, in <module>
    Lending.cancel_all()
  File "/home/linear/poloniexlendingbot/modules/Lending.py", line 200, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/home/linear/poloniexlendingbot/modules/Bitfinex.py", line 142, in return_open_loan_offers
    bfx_resp = self._post('offers')
  File "/home/linear/poloniexlendingbot/modules/ExchangeApi.py", line 29, in new_method
    return method(self, *arg, **kws)
  File "/home/linear/poloniexlendingbot/modules/Bitfinex.py", line 110, in _post
    return self._request('post', payload['request'], signed_payload, verify)
  File "/home/linear/poloniexlendingbot/modules/Bitfinex.py", line 99, in _request
    raise ex
ConnectionError: HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/offers (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f31f6760fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

v334
 Unhandled error, please open a Github issue so we can fix it!

**Comment by linearniyali** [comment]
DNS and network seem to work just fine.

$ nslookup api.bitfinex.com
Server:         192.168.0.1
Address:        192.168.0.1#53

Non-authoritative answer:
Name:   api.bitfinex.com
Address: 104.16.175.181
Name:   api.bitfinex.com
Address: 104.16.172.181
Name:   api.bitfinex.com
Address: 104.16.173.181
Name:   api.bitfinex.com
Address: 104.16.171.181
Name:   api.bitfinex.com
Address: 104.16.174.181


$ ping -c3 api.bitfinex.com
'PING api.bitfinex.com (104.16.175.181) 56(84) bytes of data.
64 bytes from 104.16.175.181 (104.16.175.181): icmp_seq=1 ttl=54 time=20.8 ms
64 bytes from 104.16.175.181 (104.16.175.181): icmp_seq=2 ttl=54 time=16.1 ms
64 bytes from 104.16.175.181 (104.16.175.181): icmp_seq=3 ttl=54 time=22.6 ms

--- api.bitfinex.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 16.121/19.859/22.643/2.746 ms


$ curl https://api.bitfinex.com/v1/offers
{"message":"X-BFX-APIKEY header was not sent."}

**Comment by linearniyali** [comment]
ah..so I found the same issue. 
https://github.com/BitBotFactory/MikaLendingBot/issues/464

Looks like the message will only show up while starting the bot.
The bot is working as expected. 
Sorry to bother.
